version: '3.0'
services:
  letsencrypt-nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/initial.conf.template:/nginx.conf.template
      - /docker-volumes/data/letsencrypt:/usr/share/nginx/html
    command: /bin/bash -c "envsubst '$$JENKINS_HOST' < /nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - JENKINS_HOST